services:
    PhilTenno\FileSyncGo\Controller\TriggerController:
        arguments:
            $tokenVerifier: '@PhilTenno\FileSyncGo\Security\TokenVerifier'
            $rateLimiter:   '@PhilTenno\FileSyncGo\Rate\RateLimiter'
            $logger:        '@monolog.logger.contao.filesyncgo' # ensure this monolog channel exists
            $container:     '@service_container'
            $projectDir:    '%kernel.project_dir%'
        tags: ['controller.service_arguments']

    # Basic service registrations (autowire so DI will resolve constructor args)
    PhilTenno\FileSyncGo\Security\TokenVerifier:
        autowire: true
        public: false

    PhilTenno\FileSyncGo\Rate\RateLimiter:
        autowire: true
        public: false